version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true